site_name: ArPiRobot
nav:
    - Downloads: downloads.md
    - Setup:
        - Raspberry Pi Setup: setup/pisetup.md
        - Setup for Development: setup/devsetup.md
        - Basic Walkthrough: setup/basicwalkthrough.md
    - Guide:
        - Programming The Robot: guide/intro.md
        - Using Motors: guide/motors.md
        - Using Sensors: guide/sensors.md
        - Using an Arduino Co-processor: guide/arduino.md
        - Supported Sensors: guide/supportedsensors.md
    - Advanced:
        - Building a Minimal ArPiRobot Image: advanced/buildminimage.md
        - Image to/from SD Card: advanced/imagefromsd.md
