site_name: ArPiRobot
site_url: https://arpirobot.gitlab.io/
theme: cinder
extra_css:
    - css/codetabs.css
markdown_extensions:
  - attr_list
  - markdown_fenced_code_tabs:
      single_block_as_tab: False
      active_class: 'active'
      template: 'default'
  - markdown_include.include:
        base_path: docs
nav:
    - Home: index.md
    - Downloads: 
        - Latest: downloads/latest.md
        - Beta Downloads: downloads/betas.md
        - Old Beta Downloads: downloads/betas-old.md
    - Guide:
        - Components & Hardware:
            - What Hardware Do I Need: guide/hardware/requiredhardware.md
            - Supported Robot Hardware: guide/hardware/supportedhardware.md
            - Example Robot Builds: guide/hardware/examplebuilds.md
        - Setup:
            - Programming Languages: guide/starting/languages.md
            - Setup your Computer: guide/starting/devsetup.md
            - Setup the Raspberry Pi: guide/starting/setuppi.md
        - Programming the Robot:
            - Starting With C++: none
            - Starting With Python: none
            - Starting With Java: none
        - Example Robot Code:
            - Intro: none
            - Arcade Drive: none
            - Voltage Monitor: none
            - Sensors: none
            - Line Following Robot: none
            - Automated Routines: none
            - Mecanum Drive: none

        
    - Reference:
        - Programming:
            - Programming Models: reference/programming_models.md
            - Robot Classes: reference/robotclasses.md
            - Motors: reference/motors.md
            - Raspberry Pi Sensors: reference/sensors.md
            - Arduino Coprocessor and Sensors: reference/arduinosensors.md
            - Media on Robots: reference/media.md
            - Network Table: reference/nettable.md
        - Guides / Manuals:
            - Drive Station Manual: reference/drive_station.md
            - Deploy Tool Manual: reference/deploy_tool.md
            - Mobile Drive Station Manual: reference/android_drive_station.md
            - Arduino IMU Calibration: reference/arduino_imu_calibration.md
        - Default Settings: reference/defaultsettings.md
    - Documentation:
        - ArPiRobot-CoreLib C++ Library: doxygen-docs/cpp/html/index.html
        - ArPiRobot-CoreLib Python Library: doxygen-docs/python/html/index.html
    - For Developers: 
        - ArPiRobot Components: devs/components.md
        - Development Resources: devs/resources.md
        - WiFi Debugging: devs/wifidebug.md
        - PythonLib Development: devs/developing_pylib.md
        - JavaLib Development: devs/developing_javalib.md
        - Building an ArPiRobot Image: devs/buildimage.md
        - Image to/from SD Card: devs/imagefromsd.md
        - Technical Documentation: devs/technical.md
