site_name: ArPiRobot
site_url: https://arpirobot.gitlab.io/
theme: cinder
extra_css:
    - css/codetabs.css
markdown_extensions:
  - attr_list
  - markdown_fenced_code_tabs:
      single_block_as_tab: False
      active_class: 'active'
      template: 'default'
  - markdown_include.include:
        base_path: docs
nav:
    - Home: index.md
    - Downloads: 
        - Latest: downloads/latest.md
        - Beta Downloads: downloads/betas.md
        - Old Beta Downloads: downloads/betas-old.md
    - Guide:
        - Components & Hardware:
            - What Hardware Do I Need: guide/hardware/requiredhardware.md
            - Supported Robot Hardware: guide/hardware/supportedhardware.md
            - Example Robot Builds: guide/hardware/examplebuilds.md
        - Setup:
            - Programming Languages: guide/starting/languages.md
            - Setup your Computer: guide/starting/devsetup.md
            - Setup the Raspberry Pi: guide/starting/setuppi.md
        - Programming the Robot:
            - Starting With C++: guide/programming/startingcpp.md
            - Starting With Python: guide/programming/startingpython.md
            - Programming Models: guide/programming/programming_models.md
        - Example Robot Code:
            - Intro: none.md
            - Arcade Drive: none.md
            - Voltage Monitor: none.md
            - Sensors & NetworkTable: none.md
            - Line Following Robot: none.md
            - Automated Routines: none.md
            - Mecanum Drive: none.md
            - Playing Audio: guide/examples/audio.md
        - Manuals:
            - Drive Station Manual: guide/manuals/drive_station.md
            - Deploy Tool Manual: guide/manuals/deploy_tool.md
            - Mobile Drive Station Manual: guide/manuals/android_drive_station.md
        
    - Documentation:
        - ArPiRobot-CoreLib C++ Library API: doxygen-docs/cpp/html/index.html
        - ArPiRobot-CoreLib Python Library API: doxygen-docs/python/html/index.html
        - Default Settings: defaultsettings.md
    
    - For Developers: 
        - ArPiRobot Components: devs/components.md
        - Development Resources: devs/resources.md
        - WiFi Debugging: devs/wifidebug.md
        - CoreLib Development: devs/developing_corelib.md
        - Building an ArPiRobot Image: devs/buildimage.md
        - Image to/from SD Card: devs/imagefromsd.md
        - Running Raspberry Pi OS Image in QEMU: devs/quemu_image.md
        - Technical Documentation: devs/technical.md
