site_name: ArPiRobot
nav:
    - Downloads: downloads.md
    - Setup:
        - Getting Started: setup/gettingstarted.md
        - Setup for Development: setup/devsetup.md
        - Update the Development Environment: setup/basicwalkthrough.md
    - Reference:
        - ArPiRobot Components: reference/components.md
        - Robot Classes: reference/robotclasses.md
        - Motors: reference/motors.md
        - Raspberry Pi Sensors: reference/sensors.md
        - Arduino Coprocessor and Sensors: reference/arduinosensors.md
        - Media on Robots: reference/media.md
        - Network Table: reference/nettable.md
        - Supported Hardware: reference/hardware.md
    - Advanced:
        - Building a Minimal ArPiRobot Image: advanced/buildminimage.md
        - Image to/from SD Card: advanced/imagefromsd.md
