site_name: ArPiRobot
nav:
    - Downloads: downloads.md
    - Setup:
        - Setup the Raspberry Pi: setup/setuppi.md
        - Setup your Computer: setup/devsetup.md
        - Installing Updates: setup/updating.md
        - Create a Simple Robot Project: setup/createproject.md
    - Reference:
        - ArPiRobot Components: reference/components.md
        - Robot Classes: reference/robotclasses.md
        - Motors: reference/motors.md
        - Raspberry Pi Sensors: reference/sensors.md
        - Arduino Coprocessor and Sensors: reference/arduinosensors.md
        - Media on Robots: reference/media.md
        - Network Table: reference/nettable.md
        - Supported Hardware: reference/hardware.md
    - Advanced:
        - Building an ArPiRobot Image: advanced/buildminimage.md
        - Image to/from SD Card: advanced/imagefromsd.md
    - For Developers: devs.md