site_name: ArPiRobot
site_url: https://arpirobot.gitlab.io/
extra_css:
  - css/extra.css
theme:
  name: material
  features:
    - navigation.tabs
  palette: 
    - scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate 
      primary: teal
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - markdown_include.include:
        base_path: docs
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
plugins:
  - search
  - redirects:
      redirect_maps:
        'downloads/latest.md': 'downloads/v1_0.md'
nav:
    - Home: index.md
    - Downloads: 
        - Version 1.0 Downloads: downloads/v1_0.md
        - Beta Downloads: downloads/betas.md
    - Guide:
        - Getting Started: guide/gettingstarted.md
        - Building a Robot:
          - Required Components: guide/hardware/requiredhardware.md
          - Supported Hardware: guide/hardware/supportedhardware.md
          - Example Robot Builds: guide/hardware/examplebuilds.md
        - Software Setup:
            - Setup your Development Computer: guide/setup/setupcomputer.md
            - Setup the Robot's Main Computer: guide/setup/setuppi.md
        - Programming the Robot:
            - Creating a Project: guide/programming/createproject.md
            - Moving Motors: guide/programming/movingmotors.md
            - Driving with Gamepad: guide/programming/drivegamepad.md
            - Sensor Data & NetworkTable: guide/programming/sensordata.md
            - Using Actions: guide/programming/actions.md
            - Using Sensors with Actions: guide/programming/sensoractions.md
            - PID Controller: guide/programming/pid.md
            - Examples Repo: guide/programming/examplesrepo.md
        - Other Tasks:
            - Playing Audio: guide/other/audio.md
            - Camera Streaming: guide/other/camstream.md
            - Connect by SSH: guide/other/ssh.md
            - WiFi Debugging: guide/other/wifidebug.md
        - Custom Parts:
            - TT Motor Quadrature Encoder: guide/custom/quadencoder.md
    - Documentation:
        - Manuals:
            - Drive Station Manual: ref/manuals/drive_station.md
            - Deploy Tool Manual: ref/manuals/deploy_tool.md
            - Mobile Drive Station Manual: ref/manuals/android_drive_station.md
        - Programming Reference:
            - Project Structure: ref/projectstructure.md
            - BaseRobot: ref/baserobot.md
            - Devices: ref/devices.md
            - Arduino Sensor Coprocessor: ref/arduino.md
            - Network Table: ref/nettable.md
            - Action System: ref/actionsystem.md
        - CoreLib API Docs:
            - Doxygen (C++): ../doxygen-docs/cpp/html/index.html
            - Doxygen (Python): ../doxygen-docs/python/html/index.html
        - Default Robot Settings: defaultsettings.md
    - Framework Developers: 
        - Overview: devs/overview.md
        - Core Library (CoreLib): devs/corelib.md
        - Arduino Firmware: devs/arduinofw.md
        - OS Image Description: devs/os_image_config.md
        - VSCode Extension: devs/vsc_extension.md
        - Building Toolchains: devs/toolchains.md
        - Publish New Release: devs/new_release.md