site_name: ArPiRobot
theme:
  name: null
  custom_dir: cinder
  colorscheme: github
  highlightjs: true
markdown_extensions:
  - attr_list
nav:
    - Home: index.md
    - Downloads: downloads.md
    - Getting Started:
        - What Hardware Do I Need: starting/requiredhardware.md
        - Supported Robot Hardware: starting/supportedhardware.md
        - Example Robot Builds: starting/examplebuilds.md
    - Setup:
        - Setup the Raspberry Pi: setup/setuppi.md
        - Setup your Computer: setup/devsetup.md
        - Installing Updates: setup/updating.md
        - Create a Simple Robot Project: setup/createproject.md
    - Reference:
        - Programming:
            - Programming Models: reference/programming_models.md
            - Robot Classes: reference/robotclasses.md
            - Motors: reference/motors.md
            - Raspberry Pi Sensors: reference/sensors.md
            - Arduino Coprocessor and Sensors: reference/arduinosensors.md
            - Media on Robots: reference/media.md
            - Network Table: reference/nettable.md
        - Guides / Manuals:
            - Drive Station Manual: reference/drive_station.md
            - Deploy Tool Manual: reference/deploy_tool.md
            - Mobile Drive Station Manual: reference/android_drive_station.md
        - Default Settings: reference/defaultsettings.md
    - For Developers: 
        - ArPiRobot Components: devs/components.md
        - Development Resources: devs/resources.md
        - WiFi Debugging: devs/wifidebug.md
        - PythonLib Development: devs/developing_pylib.md
        - Building an ArPiRobot Image: devs/buildimage.md
        - Image to/from SD Card: devs/imagefromsd.md
        - Technical Documentation: devs/technical.md