site_name: ArPiRobot
site_url: https://arpirobot.gitlab.io/
extra_css:
  - css/extra.css
theme:
  name: material
  features:
    - navigation.tabs
  palette: 
    - scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate 
      primary: teal
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - markdown_include.include:
        base_path: docs
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
nav:
    - Home: index.md
    - Downloads: 
        - Latest: downloads/latest.md
        - Beta Downloads: downloads/betas.md
        - Old Beta Downloads: downloads/betas-old.md
    - Guide:
        - Getting Started: guide/gettingstarted.md
        - Building a Robot:
          - Required Components: guide/hardware/requiredhardware.md
          - Supported Hardware: guide/hardware/supportedhardware.md
          - Example Robot Builds: guide/hardware/examplebuilds.md
        - Software Setup:
            - Setup your Computer: guide/setup/setupcomputer.md
            - Setup the Raspberry Pi: guide/setup/setuppi.md
        - Programming the Robot:
            - Creating a Project: guide/programming/createproject.md
            - Moving Motors: guide/programming/movingmotors.md
            - Driving with Gamepad: guide/programming/drivegamepad.md
            - Sensor Data & NetworkTable: guide/programming/sensordata.md
            - Using Actions: guide/programming/actions.md
            - Using Sensors with Actions: guide/programming/sensoractions.md
            - PID Controller: guide/programming/pid.md
            - Examples Repo: guide/programming/examplesrepo.md
        - Other Tasks:
            - Playing Audio: guide/other/audio.md
            - Camera Streaming: guide/other/camstream.md
            - Connect by SSH: guide/other/ssh.md
            - WiFi Debugging: guide/other/wifidebug.md
        - Custom Parts:
            - TT Motor Quadrature Encoder: guide/custom/quadencoder.md
    - Documentation:
        - Manuals:
            - Drive Station Manual: ref/manuals/drive_station.md
            - Deploy Tool Manual: ref/manuals/deploy_tool.md
            - Mobile Drive Station Manual: guide/manuals/android_drive_station.md
        - Programming Reference:
            - Project Structure: ref/projstructure.md
            - Recommended Code Organization: ref/codeorg.md
            - BaseRobot & RobotProfile: ref/baserobot.md
            - Motor Controllers: ref/motors.md
            - Drive Helpers & Axis Transforms: ref/drivehelper.md
            - Network Table & Logger: ref/nettable.md
            - Raspberry Pi Sensors: ref/pisensors.md
            - Arduino Interface and Sensors: ref/arduino.md
            - Action System & Action Manager: ref/actions.md
            - PID Controller: ref/pid.md
            - AudioManger: ref/audio.md
        - CoreLib API Docs: doxygen-links.md
        - Default Robot Settings: defaultsettings.md
    - For Developers: 
        - ArPiRobot Components: devs/components.md
        - Development Resources: devs/resources.md
        - CoreLib Development: devs/developing_corelib.md
        - Building an ArPiRobot Image: devs/buildimage.md
        - Image to/from SD Card: devs/imagefromsd.md
        - Running Raspberry Pi OS Image in QEMU: devs/quemu_image.md
        - Technical Documentation: devs/technical.md
