site_name: ArPiRobot
site_url: https://arpirobot.gitlab.io/
theme: cinder
extra_css:
    - css/codetabs.css
markdown_extensions:
  - attr_list
  - markdown_fenced_code_tabs:
      single_block_as_tab: False
      active_class: 'active'
      template: 'default'
  - markdown_include.include:
        base_path: docs
nav:
    - Home: index.md
    - Downloads: 
        - Latest: downloads/latest.md
        - Beta Downloads: downloads/betas.md
        - Old Beta Downloads: downloads/betas-old.md
    - Guide:
        - Building a Robot:
            - What Hardware Do I Need: guide/hardware/requiredhardware.md
            - Supported Robot Hardware: guide/hardware/supportedhardware.md
            - Example Robot Builds: guide/hardware/examplebuilds.md
        - Software Setup:
            - Setup your Computer: guide/setup/setupcomputer.md
            - Setup the Raspberry Pi: guide/setup/setuppi.md
        - Programming the Robot:
            - First Program: none.md
            - Moving Motors: none.md
            - Driving with Gamepad: none.md
            - Sensor Data & NetworkTable: none.md
            - Using Actions: none.md
            - PID Controller: none.md
            - Examples Repo: https://github.com/ArPiRobot/ArPiRobot-Examples
        - Other Tasks:
            - Playing Audio: guide/other/audio.md
            - Camera Streaming: none.md
        - Manuals:
            - Drive Station Manual: guide/manuals/drive_station.md
            - Deploy Tool Manual: guide/manuals/deploy_tool.md
            - Mobile Drive Station Manual: guide/manuals/android_drive_station.md
        
    - Documentation:
        - ArPiRobot-CoreLib C++ Library API: doxygen-docs/cpp/html/index.html
        - ArPiRobot-CoreLib Python Library API: doxygen-docs/python/html/index.html
        - Default Settings: defaultsettings.md
    
    - For Developers: 
        - ArPiRobot Components: devs/components.md
        - Development Resources: devs/resources.md
        - WiFi Debugging: devs/wifidebug.md
        - CoreLib Development: devs/developing_corelib.md
        - Building an ArPiRobot Image: devs/buildimage.md
        - Image to/from SD Card: devs/imagefromsd.md
        - Running Raspberry Pi OS Image in QEMU: devs/quemu_image.md
        - Technical Documentation: devs/technical.md
